pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: tools
    image: docker:27.3-cli
    command: ["cat"]
    tty: true
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
  - name: dind
    image: docker:27.3-dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    ports:
      - containerPort: 2375
"""
      defaultContainer 'tools'
    }
  }

  environment {
    AWS_REGION   = "us-east-1"
    ECR_REGISTRY = "972598852792.dkr.ecr.us-east-1.amazonaws.com"
    ECR_REPO     = "tetris-app"
    IMAGE_TAG    = "${env.BUILD_NUMBER}"
    IMAGE_URI    = "${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install tools (awscli + trivy)') {
      steps {
        sh '''
          set -eux

          # docker:*-cli is alpine-based
          apk add --no-cache python3 py3-pip curl
          pip3 install --no-cache-dir awscli

          # Install Trivy (Alpine package)
          apk add --no-cache trivy

          aws --version
          trivy --version
          docker version
        '''
      }
    }

    stage('Build Docker image') {
      steps {
        sh '''
          set -eux
          docker build -t tetris-app:ci .
        '''
      }
    }

    stage('Trivy scan (fail on CRITICAL)') {
      steps {
        sh '''
          set -eux
          trivy image --exit-code 1 --severity CRITICAL tetris-app:ci
          trivy image --severity HIGH,CRITICAL tetris-app:ci
        '''
      }
    }

    stage('Login to ECR + Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws-ecr-credentials', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          sh '''
            set -eux

            aws ecr get-login-password --region ${AWS_REGION} \
              | docker login --username AWS --password-stdin ${ECR_REGISTRY}

            docker tag tetris-app:ci ${IMAGE_URI}
            docker push ${IMAGE_URI}

            docker tag tetris-app:ci ${ECR_REGISTRY}/${ECR_REPO}:latest
            docker push ${ECR_REGISTRY}/${ECR_REPO}:latest
          '''
        }
      }
    }
  }

  post {
    always {
      sh '''
        docker images | head -n 30 || true
      '''
    }
  }
}
