apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: 972598852792.dkr.ecr.us-east-1.amazonaws.com/tetris-app:latest
        ports:
        - containerPort: 80
